### ISSUE TITLE
Support standard Authorization header

### ISSUE THREAD

**Issue by unsafecode** [benMain/nest-azure-ad-jwt-validator#26]
As per subject, make the token header configurable. Most apps expect standard behavior and standard headers, as per RFC

**Comment by benMain** [comment]
@unsafecode Yeah, we wrote this under the context of api gateway, where that header isn't touchable. I can add that configuration

**Comment by KerryRitter** [comment]
Proposition: add a new property to `NestAzureAdJwtValidatorModuleOptions` named "authorizationHeader" and leverage that to get the token out of the request headers. Default to "authtoken"as to not break existing consumers. 

Open to PRs!

**Comment by benMain** [comment]
@unsafecode @KerryRitter  I'm sure you might have forked or self-implemented long ago but his is solved by version 4.0.0
