### ISSUE TITLE
change private parseTokenFromContext(context) to protected

### ISSUE THREAD

**Issue by alle42** [benMain/nest-azure-ad-jwt-validator#30]
https://github.com/benMain/nest-azure-ad-jwt-validator/blob/4a28f7b3f870ef8af5510ca8f6d13878abcc8522/src/guards/azure-active-directory.guard.ts#L51

Please change private parseTokenFromContext(context) to protected. Reason to able override method . Or change please 
const tokenHeader = request.headers.authtoken to const tokenHeader = request.headers.authorization

**Comment by KerryRitter** [comment]
Duplicate of #26. we need to allow the consumer to specify what header contains the token.
