### ISSUE TITLE
HttpService is deprecated

### ISSUE THREAD

**Issue by IsaacJara** [benMain/nest-azure-ad-jwt-validator#48]
Would it be possible to use Axios instead of HttpService due to the latter being deprecated?

![image](https://user-images.githubusercontent.com/51455769/178767061-5fcba487-a95a-45ea-858d-0d021669b082.png)

**Comment by pawelstachu** [comment]
bump

**Comment by benMain** [comment]
@IsaacJara  @pawelstachu  this has been released with version 5 for nestjs9.
